version: '3.4'

services: 
  web: 
    container_name: react-app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-dev
    environment: 
      - NODE_ENV=development
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules